#!/usr/bin/env python3
"""
Generate G-code for pedalboard case top panel (Hammond 1590DD).

All coordinates derived from pedalboard-display KiCad PCB.
Case mounted open-side-down. Z=0 = top surface, Z- = into material.

Origin modes:
  --origin center  (default) Probe both sides of case at Z=-2,
                   compute midpoint. Best accuracy.
  --origin corner  Front-left corner of top flat surface.

Usage:
    python3 top-panel-gcode.py > top-panel.nc
    python3 top-panel-gcode.py --origin corner > top-panel.nc
    python3 top-panel-gcode.py --tool-dia 3 --feed-xy 200 > top-panel.nc
"""

import argparse
import math
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from panel_coords import load_coords, cnc_coords

# === PARAMETERS ===

def parse_args():
    p = argparse.ArgumentParser(description="Pedalboard case top panel G-code generator")

    # Tool
    p.add_argument("--tool-dia", type=float, default=4.0,
                   help="Endmill diameter in mm (default: 4.0)")

    # Feeds & speeds
    p.add_argument("--feed-xy", type=float, default=300,
                   help="Cutting feed rate XY in mm/min (default: 300)")
    p.add_argument("--feed-z", type=float, default=100,
                   help="Plunge feed rate Z in mm/min (default: 100)")
    p.add_argument("--spindle-rpm", type=int, default=10000,
                   help="Spindle speed in RPM (default: 10000)")

    # Depths
    p.add_argument("--stock-thickness", type=float, default=3.5,
                   help="Case wall thickness in mm (default: 3.5)")
    p.add_argument("--depth-per-pass", type=float, default=0.3,
                   help="Depth of cut per pass in mm (default: 0.3)")
    p.add_argument("--extra-depth", type=float, default=0.2,
                   help="Extra depth below stock for clean through-cut (default: 0.2)")

    # Heights
    p.add_argument("--safe-z", type=float, default=5.0,
                   help="Safe Z height for rapids (default: 5.0)")
    p.add_argument("--retract-z", type=float, default=1.0,
                   help="Retract Z between passes (default: 1.0)")

    # Geometry overrides
    p.add_argument("--button-dia", type=float, default=22.3,
                   help="Button/encoder hole diameter (default: 22.3)")
    p.add_argument("--display-w", type=float, default=42.5,
                   help="Display cutout width (default: 42.5)")
    p.add_argument("--display-h", type=float, default=36.7,
                   help="Display cutout height (default: 36.7)")
    p.add_argument("--display-recess-w", type=float, default=44.5,
                   help="Display recess width for flush window (default: 44.5)")
    p.add_argument("--display-recess-h", type=float, default=38.7,
                   help="Display recess height for flush window (default: 38.7)")
    p.add_argument("--button-recess-dia", type=float, default=24.0,
                   help="Button LED ring recess diameter (default: 24.0)")
    p.add_argument("--recess-depth", type=float, default=1.0,
                   help="Recess depth for flush-mount parts (default: 1.0)")
    p.add_argument("--lightpipe-dia", type=float, default=6.0,
                   help="Light pipe hole diameter (default: 6.0)")
    p.add_argument("--bezel-hole-dia", type=float, default=4.0,
                   help="Bezel mounting hole diameter (default: 4.0)")
    p.add_argument("--coords", type=str, default=None,
                   help="Path to top-panel-coords.json (default: auto-detect)")
    p.add_argument("--origin", type=str, default="center", choices=["corner", "center"],
                   help="Origin mode: 'center' (probe both sides) or 'corner' (front-left) (default: center)")
    p.add_argument("--angle", type=float, default=0.0,
                   help="Fixture rotation angle in degrees CCW (default: 0.0). "
                        "Measure by probing two points on the same edge: "
                        "angle = atan2(y2-y1, x2-x1) in degrees.")
    p.add_argument("--z-offsets", type=str, default=None,
                   help="JSON file with per-feature Z offsets from probe-setup.py. "
                        "Compensates for surface curvature on cast cases.")
    p.add_argument("--displays-only", action="store_true",
                   help="Only generate display recesses and cutouts (for rework).")

    return p.parse_args()


# === GEOMETRY ===
# Loaded from top-panel-coords.json (generated by extract-coords.py)
# Origin: front-left corner of case top flat surface.
# All coordinates computed by panel_coords.cnc_coords().

def load_positions(coords_path=None, origin="center", angle_deg=0.0):
    """Load and transform all positions from JSON."""
    data = load_coords(coords_path)
    return cnc_coords(data, origin=origin, angle_deg=angle_deg)

BUTTONS = []
ENCODERS = []
DISPLAYS = []
LIGHT_PIPES = []
BEZEL_HOLES = []


# === G-CODE GENERATION ===

class GCode:
    def __init__(self, args, z_offsets=None):
        self.args = args
        self.tool_r = args.tool_dia / 2.0
        self.total_depth = args.stock_thickness + args.extra_depth
        self.lines = []
        self.z_offsets = z_offsets or {}  # {"buttons": [0.0, -0.1, ...], "encoders": [...], ...}
        self._current_z_offset = 0.0

    def emit(self, line=""):
        self.lines.append(line)

    def set_z_offset(self, feature_type, index):
        """Set the current Z offset for a feature from the offsets table."""
        offsets = self.z_offsets.get(feature_type, [])
        if index < len(offsets):
            self._current_z_offset = offsets[index]
        else:
            self._current_z_offset = 0.0

    def z(self, depth):
        """Apply current Z offset to a depth value."""
        return depth + self._current_z_offset

    def header(self):
        a = self.args
        origin_desc = "case center (probe both sides)" if a.origin == "center" else "front-left corner of top flat surface"
        self.emit(f"(Pedalboard case top panel)")
        self.emit(f"(Origin: {origin_desc})")
        self.emit(f"(Angle correction: {a.angle:.3f} deg)")
        self.emit(f"(Case mounted open-side-down)")
        self.emit(f"(Tool: {a.tool_dia}mm single flute downcut)")
        self.emit(f"(Feed XY: {a.feed_xy} mm/min, Z: {a.feed_z} mm/min)")
        self.emit(f"(Spindle: {a.spindle_rpm} RPM)")
        self.emit(f"(Stock: {a.stock_thickness}mm, depth/pass: {a.depth_per_pass}mm)")
        self.emit()
        self.emit("G21 (mm)")
        self.emit("G90 (absolute)")
        self.emit("G17 (XY plane)")
        self.emit()
        self.emit(f"M3 S{a.spindle_rpm}")
        self.emit("G4 P2 (spindle spin-up)")
        self.emit()

    def footer(self):
        self.emit()
        self.emit(f"G0 Z{self.args.safe_z}")
        self.emit("M5")
        self.emit("G0 X0 Y0")
        self.emit("M2")

    def rapid_to(self, x, y):
        self.emit(f"G0 Z{self.args.safe_z}")
        self.emit(f"G0 X{x:.3f} Y{y:.3f}")

    def circular_profile(self, cx, cy, diameter, label="", extra_depth=0.0):
        """Cut a circular through-hole using helical interpolation."""
        a = self.args
        total_depth = self.total_depth + extra_depth
        r = diameter / 2.0
        cut_r = r - self.tool_r  # toolpath radius

        if cut_r <= 0:
            # Hole smaller than or equal to tool: plunge
            self.plunge_hole(cx, cy, label)
            return

        self.emit()
        self.emit(f"({label}: circle dia {diameter}mm at X{cx:.1f} Y{cy:.1f})")

        # Rapid to start position (3 o'clock)
        start_x = cx + cut_r
        start_y = cy
        self.rapid_to(start_x, start_y)

        # Helical descent
        n_passes = math.ceil(total_depth / a.depth_per_pass)
        self.emit(f"G0 Z{a.retract_z}")

        current_z = 0
        for i in range(n_passes):
            next_z = current_z - a.depth_per_pass
            if next_z < -total_depth:
                next_z = -total_depth
            # Helical entry: circle while descending to next depth
            self.emit(f"G2 I{-cut_r:.3f} J0 Z{self.z(next_z):.3f} F{a.feed_xy}")
            current_z = next_z

        # Final full-depth pass (spring cut, no Z change)
        self.emit(f"G2 I{-cut_r:.3f} J0 F{a.feed_xy}")

        # Retract
        self.emit(f"G0 Z{a.safe_z}")

    def rectangular_profile(self, cx, cy, width, height, label=""):
        """Cut a rectangular through-hole with corner radius = tool radius."""
        a = self.args
        corner_r = self.tool_r  # minimum corner radius with this tool

        # Toolpath rectangle (offset inward by tool radius)
        hw = width / 2.0 - self.tool_r   # half-width of toolpath
        hh = height / 2.0 - self.tool_r  # half-height of toolpath

        self.emit()
        self.emit(f"({label}: rect {width}x{height}mm at X{cx:.1f} Y{cy:.1f}, corner R{corner_r:.1f})")

        # Start at mid-point of bottom edge
        start_x = cx
        start_y = cy - hh
        self.rapid_to(start_x, start_y)

        n_passes = math.ceil(self.total_depth / a.depth_per_pass)
        self.emit(f"G0 Z{a.retract_z}")

        # Continuous spiral descent around the rectangle (like helical circles)
        # Each full loop descends one pass depth, distributed across 4 sides
        current_z = float(a.retract_z)  # start from retract height
        for i in range(n_passes):
            next_z = -(i + 1) * a.depth_per_pass
            if next_z < -self.total_depth:
                next_z = -self.total_depth
            dz_per_side = (next_z - current_z) / 4.0

            self.emit(f"G1 X{cx + hw:.3f} Y{cy - hh:.3f} Z{self.z(current_z + dz_per_side * 1):.3f} F{a.feed_xy}")
            self.emit(f"G1 X{cx + hw:.3f} Y{cy + hh:.3f} Z{self.z(current_z + dz_per_side * 2):.3f}")
            self.emit(f"G1 X{cx - hw:.3f} Y{cy + hh:.3f} Z{self.z(current_z + dz_per_side * 3):.3f}")
            self.emit(f"G1 X{cx - hw:.3f} Y{cy - hh:.3f} Z{self.z(current_z + dz_per_side * 4):.3f}")
            current_z = next_z

        # Return to start position at final depth
        self.emit(f"G1 X{cx:.3f} Y{cy - hh:.3f} F{a.feed_xy}")

        # Spring pass at full depth (flat, no Z change)
        self.emit(f"G1 X{cx + hw:.3f} Y{cy - hh:.3f} F{a.feed_xy}")
        self.emit(f"G1 X{cx + hw:.3f} Y{cy + hh:.3f}")
        self.emit(f"G1 X{cx - hw:.3f} Y{cy + hh:.3f}")
        self.emit(f"G1 X{cx - hw:.3f} Y{cy - hh:.3f}")
        self.emit(f"G1 X{cx:.3f} Y{cy - hh:.3f}")

        self.emit(f"G0 Z{a.safe_z}")

    def plunge_hole(self, cx, cy, label=""):
        """Plunge-drill a hole equal to tool diameter."""
        a = self.args
        self.emit()
        self.emit(f"({label}: plunge dia {a.tool_dia}mm at X{cx:.1f} Y{cy:.1f})")
        self.rapid_to(cx, cy)
        self.emit(f"G0 Z{a.retract_z}")

        # Peck drill
        current_z = 0
        peck = a.depth_per_pass * 2  # pecks can be deeper for plunge
        while current_z > -self.total_depth:
            current_z -= peck
            if current_z < -self.total_depth:
                current_z = -self.total_depth
            self.emit(f"G1 Z{self.z(current_z):.3f} F{a.feed_z}")
            self.emit(f"G0 Z{a.retract_z}")

        # Final plunge
        self.emit(f"G1 Z{self.z(-self.total_depth):.3f} F{a.feed_z}")
        self.emit(f"G0 Z{a.safe_z}")

    def circular_pocket(self, cx, cy, diameter, depth, label=""):
        """Cut a circular pocket (recess) to a specified depth."""
        a = self.args
        r = diameter / 2.0
        cut_r = r - self.tool_r

        if cut_r <= 0:
            return  # can't pocket smaller than tool

        self.emit()
        self.emit(f"({label}: circular pocket dia {diameter}mm, {depth}mm deep at X{cx:.1f} Y{cy:.1f})")

        start_x = cx + cut_r
        start_y = cy
        self.rapid_to(start_x, start_y)

        n_passes = math.ceil(depth / a.depth_per_pass)
        self.emit(f"G0 Z{a.retract_z}")

        current_z = 0
        for i in range(n_passes):
            next_z = current_z - a.depth_per_pass
            if next_z < -depth:
                next_z = -depth
            # Helical entry: circle while descending
            self.emit(f"G2 I{-cut_r:.3f} J0 Z{self.z(next_z):.3f} F{a.feed_xy}")
            current_z = next_z

        # Spring pass
        self.emit(f"G2 I{-cut_r:.3f} J0 F{a.feed_xy}")
        self.emit(f"G0 Z{a.safe_z}")

    def rectangular_pocket(self, cx, cy, width, height, depth, label=""):
        """Cut a rectangular pocket (recess) to a specified depth."""
        a = self.args
        corner_r = self.tool_r

        hw = width / 2.0 - self.tool_r
        hh = height / 2.0 - self.tool_r

        self.emit()
        self.emit(f"({label}: rect pocket {width}x{height}mm, {depth}mm deep at X{cx:.1f} Y{cy:.1f})")

        start_x = cx
        start_y = cy - hh
        self.rapid_to(start_x, start_y)

        n_passes = math.ceil(depth / a.depth_per_pass)
        self.emit(f"G0 Z{a.retract_z}")

        # Continuous spiral descent
        current_z = 0
        for i in range(n_passes):
            next_z = current_z - a.depth_per_pass
            if next_z < -depth:
                next_z = -depth
            dz_per_side = (next_z - current_z) / 4.0

            self.emit(f"G1 X{cx + hw:.3f} Y{cy - hh:.3f} Z{self.z(current_z + dz_per_side * 1):.3f} F{a.feed_xy}")
            self.emit(f"G1 X{cx + hw:.3f} Y{cy + hh:.3f} Z{self.z(current_z + dz_per_side * 2):.3f}")
            self.emit(f"G1 X{cx - hw:.3f} Y{cy + hh:.3f} Z{self.z(current_z + dz_per_side * 3):.3f}")
            self.emit(f"G1 X{cx - hw:.3f} Y{cy - hh:.3f} Z{self.z(current_z + dz_per_side * 4):.3f}")
            current_z = next_z

        # Return to start + spring pass at full depth
        self.emit(f"G1 X{cx:.3f} Y{cy - hh:.3f} F{a.feed_xy}")
        self.emit(f"G1 X{cx + hw:.3f} Y{cy - hh:.3f}")
        self.emit(f"G1 X{cx + hw:.3f} Y{cy + hh:.3f}")
        self.emit(f"G1 X{cx - hw:.3f} Y{cy + hh:.3f}")
        self.emit(f"G1 X{cx - hw:.3f} Y{cy - hh:.3f}")
        self.emit(f"G1 X{cx:.3f} Y{cy - hh:.3f}")
        self.emit(f"G1 X{cx + hw:.3f} Y{cy - hh:.3f} F{a.feed_xy}")
        self.emit(f"G1 X{cx + hw:.3f} Y{cy + hh:.3f}")
        self.emit(f"G1 X{cx - hw:.3f} Y{cy + hh:.3f}")
        self.emit(f"G1 X{cx - hw:.3f} Y{cy - hh:.3f}")
        self.emit(f"G1 X{cx:.3f} Y{cy - hh:.3f}")

        self.emit(f"G0 Z{a.safe_z}")

    def generate(self):
        a = self.args
        self.header()

        # 1. Light pipe holes (dia 6mm through, plexiglass disc press-fits in)
        if not a.displays_only:
            for i, (x, y) in enumerate(LIGHT_PIPES):
                self.set_z_offset("single_leds", i)
                self.circular_profile(x, y, a.lightpipe_dia, f"Light pipe {i+1}")

            # 2. Button/encoder recesses
            for i, (x, y) in enumerate(BUTTONS):
                self.set_z_offset("buttons", i)
                self.circular_pocket(x, y, a.button_recess_dia, a.recess_depth,
                                     f"Button {i+1} recess")
            for i, (x, y) in enumerate(ENCODERS):
                self.set_z_offset("encoders", i)
                self.circular_pocket(x, y, a.button_recess_dia, a.recess_depth,
                                     f"Encoder {i+1} recess")

            # 3. Button/encoder through-holes
            for i, (x, y) in enumerate(BUTTONS):
                self.set_z_offset("buttons", i)
                # Button 4 (index 3) cuts 3mm deeper to clear center screw post
                extra = 3.0 if i == 3 else 0.0
                self.circular_profile(x, y, a.button_dia, f"Button {i+1}", extra_depth=extra)

            for i, (x, y) in enumerate(ENCODERS):
                self.set_z_offset("encoders", i)
                self.circular_profile(x, y, a.button_dia, f"Encoder {i+1}")

        # 4. Display recesses (asymmetric: 5mm extra toward center, 3mm extra toward edge in X)
        #    + 2.6mm shift toward back (positive X) for connector clearance
        display_offset_x = -2.6  # mm toward back (negative X) for connector clearance
        for i, (x, y) in enumerate(DISPLAYS):
            self.set_z_offset("displays", i)
            # Asymmetric enlargement shift (1mm toward center)
            x_shift = -1.0 if x > 0 else 1.0
            self.rectangular_pocket(x + x_shift + display_offset_x, y, a.display_recess_w, a.display_recess_h,
                                    a.recess_depth, f"Display {i+1} recess")

        # 5. Display through-cutouts (same shifts)
        for i, (x, y) in enumerate(DISPLAYS):
            self.set_z_offset("displays", i)
            x_shift = -1.0 if x > 0 else 1.0
            self.rectangular_profile(x + x_shift + display_offset_x, y, a.display_w, a.display_h, f"Display {i+1}")

        self.footer()
        return "\n".join(line for line in self.lines if line and not line.startswith("("))


if __name__ == "__main__":
    args = parse_args()

    # Load positions from JSON
    coords = load_positions(args.coords, origin=args.origin, angle_deg=args.angle)
    BUTTONS = coords["buttons"]
    ENCODERS = coords["encoders"]
    DISPLAYS = coords["displays"]
    LIGHT_PIPES = coords["single_leds"]
    BEZEL_HOLES = coords["bezel_holes"]

    # Override feature sizes from JSON if not specified on command line
    # (command line args take precedence via argparse defaults)

    # Validate
    if args.tool_dia > args.lightpipe_dia:
        print(f"WARNING: Tool dia {args.tool_dia}mm > light pipe hole dia {args.lightpipe_dia}mm, "
              f"will plunge (hole = tool diameter)", file=sys.stderr)
    if args.tool_dia > args.bezel_hole_dia:
        print(f"WARNING: Tool dia {args.tool_dia}mm > bezel hole dia {args.bezel_hole_dia}mm, "
              f"will plunge (hole = tool diameter)", file=sys.stderr)

    # Load Z offsets if provided
    z_offsets = {}
    if args.z_offsets:
        import json as json_mod
        with open(args.z_offsets) as f:
            z_offsets = json_mod.load(f)
        print(f"Loaded Z offsets from {args.z_offsets}", file=sys.stderr)

    gc = GCode(args, z_offsets=z_offsets)
    output = gc.generate()

    # Validate G-code for grblHAL compatibility
    errors = []
    for i, line in enumerate(output.splitlines(), 1):
        if not line.isascii():
            errors.append(f"  Line {i}: non-ASCII character: {repr(line)}")
        if line.strip() == "":
            errors.append(f"  Line {i}: empty line")
        if line.startswith("("):
            errors.append(f"  Line {i}: comment line (may cause error:1 on grblHAL)")
        if len(line) > 70:
            errors.append(f"  Line {i}: line too long ({len(line)} chars): {line[:50]}...")
    if errors:
        print("G-code validation FAILED:", file=sys.stderr)
        for e in errors:
            print(e, file=sys.stderr)
        sys.exit(1)

    print(output)
